//
//  GetStudentStudentInformation.swift
//  OnTheMapV.2
//
//  Created by mairo on 03/12/2022.
//

import Foundation

// MARK: 4. Parse API: What is a Student Location?
// MARK: B.2. "StudentInformation" struct to store individual locations and links downloaded from the service

struct GetStudentInformation: Codable { // In Parse, each StudentLocation is represented as a collection of key/value pairs (Parse Types are String, String?, Double):
    
    struct StudentLocationData: Codable {
        
        let objectId: String? /* // MARK: 1. id
                               Description: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
                               Example Value: 8ZExGR5uX8 */
        
        let uniqueKey: String /* // MARK: 2. extra (optional) id
                                Description: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
                                Example Value: 1234 */
        
        let firstName: String /* // MARK: 3. name
                               Description: the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in your app (see above)
                               Example Value: Juliette */
        
        let lastName: String /* // MARK: 4. surname
                              Description: the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in your app (see above)
                              Example Value: Voel */
        
        let mapString: String /* // MARK: 5. address
                               Description: the location string used for geocoding the student location
                               Example Value: Mountain View, CA */
        
        let mediaURL: String /* // MARK: 6. link
                              Description: the URL provided by the student
                              Example Value: https://udacity.com */
        
        let latitude: Double /* // MARK: 7. y
                              Description: the latitude of the student location (ranges from -90 to 90)
                              Example Value: 37.386052 */
        
        let longitude: Double /* // MARK: 8. x
                               Description: the longitude of the student location (ranges from -180 to 180)
                               Example Value: -122.083851 */
        
        // parsing data or ACL are not neccessary:
        
        let createdAt: String? /* // MARK: 9. created
                               Description: the date when the student location was created
                               Parse Type: Date
                               Example Value: Feb 25, 2015, 01:10 */
        
        let updatedAt: String? /* // MARK: 10. updated
                               Description: the date when the student location was last updated
                               Parse Type: Date
                               Example Value: Mar 09, 2015, 23:34 */
        
        /*
         let ACL: acl_type_t /* // MARK: 11. ?
                              Description: the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry
                              Parse Type: ACL
                              Example Value: Public Read and Write */
         */
        
    }
        
    let results: [StudentLocationData]
        
}

// 5. Parse API: GETting Student Locations
// Example JSON Response from: https://video.udacity-data.com/topher/2016/June/57583b20_get-student-locations/get-student-locations.json

/*
 {
     "results":[
         {
             "createdAt": "2015-02-25T01:10:38.103Z",
             "firstName": "Jarrod",
             "lastName": "Parkes",
             "latitude": 34.7303688,
             "longitude": -86.5861037,
             "mapString": "Huntsville, Alabama ",
             "mediaURL": "https://www.linkedin.com/in/jarrodparkes",
             "objectId": "JhOtcRkxsh",
             "uniqueKey": "996618664",
             "updatedAt": "2015-03-09T22:04:50.315Z"
         }
         {
             "createdAt":"2015-02-24T22:27:14.456Z",
             "firstName":"Jessica",
             "lastName":"Uelmen",
             "latitude":28.1461248,
             "longitude":-82.756768,
             "mapString":"Tarpon Springs, FL",
             "mediaURL":"www.linkedin.com/in/jessicauelmen/en",
             "objectId":"kj18GEaWD8",
             "uniqueKey":"872458750",
             "updatedAt":"2015-03-09T22:07:09.593Z"
         },
         {
             "createdAt":"2015-02-24T22:30:54.442Z",
             "firstName":"Jason",
             "lastName":"Schatz",
             "latitude":37.7617,
             "longitude":-122.4216,
             "mapString":"18th and Valencia, San Francisco, CA",
             "mediaURL":"http://en.wikipedia.org/wiki/Swift_%28programming_language%29",
             "objectId":"hiz0vOTmrL",
             "uniqueKey":"2362758535",
             "updatedAt":"2015-03-10T17:20:31.828Z"
         },
         {
             "createdAt": "2015-02-24T22:35:30.639Z",
             "firstName": "Gabrielle",
             "lastName": "Miller-Messner",
             "latitude": 35.1740471,
             "longitude": -79.3922539,
             "mapString": "Southern Pines, NC",
             "mediaURL": "http://www.linkedin.com/pub/gabrielle-miller-messner/11/557/60/en",
             "objectId": "8ZEuHF5uX8",
             "uniqueKey": "2256298598",
             "updatedAt": "2015-03-09T22:06:11.615Z"
         }
     ]
 }
 */

